/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f103xb.h"
#include <stdint.h>
#include "bl_jump.h"
#include "usart1.h"
#include "dwt.h"

int main(void)
{
  USART1_Init();
  DWT_Init();

  USART1_SendString("Bootloader Started\r\n");

  BootloaderError_t err = Bootloader_Is_App_Valid();

  switch (err)
  {
    case BOOT_SUCCESS:
      USART1_SendString("App Valid - Jumping...\r\n");
      DWT_Delay_ms(10);
      Jump_To_Application();
      break;

    case MAGIC_ERROR:
      USART1_SendString("Magic Error\r\n");
      break;

    case CRC_ERROR:
      USART1_SendString("CRC Error\r\n");
      break;

    case RESET_ERROR:
      USART1_SendString("Reset Error\r\n");
      break;

    case SIZE_ERROR:
      USART1_SendString("Size Error\r\n");
      break;
  }

  USART1_SendString("Staying in Bootloader\r\n");

  while(1)
  {

  }
}
